import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    java
    `maven-publish`
    kotlin("jvm") version "1.3.70"

    id("com.github.johnrengelman.shadow") version "5.2.0"
}

repositories {
    mavenLocal()
    mavenCentral()

    // Spigot
    maven("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")

    // Dynmap
    maven("https://repo.mikeprimm.com/")

//    maven {
//        url = 'http://catageek.free.fr/bytecart/maven/repositories/releases/'
//    }

//    maven {
//        url = 'http://catageek.free.fr/bytecart/maven/repositories/snapshots/'
//    }

}

group = "nl.jboi.minecraft"
description = "ByteCart"
version = "3.3.0"

dependencies {
    implementation(kotlin("stdlib-jdk8"))
    implementation("us.dynmap:dynmap-api:2.5") { isTransitive = false }
    implementation("com.google.code.gson:gson:2.8.0")
    implementation(project(":ByteCartAPI"))
    compileOnly("org.bukkit:bukkit:1.14.4+")
}

allprojects {
    this.group = rootProject.group
    this.version = rootProject.version
}

subprojects {
    afterEvaluate {
        publishing {
            publications {
                create<MavenPublication>(project.name) {
                    from(project.components["java"])
                }
            }
        }
    }
}

publishing {
    publications {
        create<MavenPublication>(project.name) {
            artifact(tasks["shadowJar"])
        }
    }
}

tasks {
    jar {
        archiveClassifier.set("bare")
        dependsOn(":shadowJar")
    }

    shadowJar {
        archiveClassifier.set(null as String?)
    }
}

val compileKotlin: KotlinCompile by tasks
compileKotlin.kotlinOptions {
    jvmTarget = "1.8"
}

val compileTestKotlin: KotlinCompile by tasks
compileTestKotlin.kotlinOptions {
    jvmTarget = "1.8"
}

tasks.withType(JavaCompile::class.java) {
    options.encoding = "UTF-8"
}
